### ISSUE TITLE
Add nanoPharos datasets (direct link) to BioSchemas

### ISSUE THREAD

**Issue by novamechanicsdev** [NanoCommons/datasets#14]
for the links please see NanoCommons deliverable 4.7 (page 87): https://docs.google.com/document/d/1wv1bUlk5DoLDtFtX8jZeLGrw5QvtIMU61LWO1J6YsLM/edit#

**Comment by egonw** [comment]
I still need to explore how to best do this, sorry.

**Comment by egonw** [comment]
Let's get them all listed here: https://github.com/NanoSolveIT/datasets
